### ISSUE TITLE
In “Site > Settings > Site Details” for Intel Mac version, “PHP Version” appears as “WP Version”.

### ISSUE THREAD

**Issue by stein2nd** [Automattic/studio#729] opened 2024-12-10 08:30 UTC
### Quick summary

The About Info screen of the version in which the phenomenon is occurring.
![Image](https://github.com/user-attachments/assets/33d6aa8a-2f62-4f43-895d-de11f8240158)

Two “WP versions” are shown; the second one should correctly show “PHP version.”
![Image](https://github.com/user-attachments/assets/d33396c7-d9a4-4294-9821-91de3d8d0bc3)

### Steps to reproduce

1. Start the Studio.app.
2. Go to the “Settings” tab.
3. Check each item in the “Site Details” block.

### What you expected to happen

WordPress version and PHP version are properly displayed.

### What actually happened

The PHP version is probably correct, but improperly displayed: i.e., WordPress, not PHP.
![Image](https://github.com/user-attachments/assets/b9bc1a27-fdeb-45f8-a923-1dc06fdf3654)

### Impact

All

### Available workarounds?

No and the app is unusable

**Comment by wojtekn** [comment] 2024-12-10 09:51
Thanks for reporting the issue @stein2nd . It looks it was caused by a duplicated and incorrect translation entry, which was overwriting the correct one:

![Image](https://github.com/user-attachments/assets/2d750240-6bc5-4c7d-ab17-70af8dd347f6)

I've just removed it, so it will get fixed in the next release.

**Closed as completed by wojtekn** 2024-12-10 09:51 UTC
