### ISSUE TITLE
Vietnamese display error - Character spacing

### ISSUE THREAD

**Issue by nguyenquanghoang** [Automattic/studio#372] opened 2024-07-19 13:42 UTC
### Quick summary

Is there any way to fix the space between 2 paragraphs of text for languages ​​that have more characters than English? (Specifically, the characters when translated from English to Vietnamese will be longer, making the distance very difficult to see)

![Fix Show Text - Studio](https://github.com/user-attachments/assets/e314ea94-cb59-4c93-ace0-861c33468b8f)

### Steps to reproduce

1. Start the Studio app.
2. At the site running position and Stop all (When using Vietnamese, it will be very difficult to see and act)

### What you expected to happen

Create a more visible distance for Vietnamese

### What actually happened

Vietnamese display error 

### Impact

All

### Available workarounds?

There is no user impact

### Platform

Windows

### Logs or notes

Suggestion: Sidebar can be expanded when the number of characters is larger

**Comment by nguyenquanghoang** [comment] 2024-07-19 13:51
In addition, these 3 positions do not have a translation String to understand Vietnamese

![Fix not show vietnamese - Studio](https://github.com/user-attachments/assets/554c08b8-3307-4bc7-a244-da9449309f6c)

**Comment by nguyenquanghoang** [comment] 2024-07-22 06:28
@wojtekn When I use Windows with English language, is there any way to optionally display Vietnamese on Studio?

**Comment by wojtekn** [comment] 2024-07-22 08:30
@nguyenquanghoang there is no language selector in Studio yet, and it follows the OS language instead. There is [a feature request to add that](https://github.com/Automattic/studio/issues/25), though.

On macOS it's possible to change language for a single app on the OS level, but Windows doesn't provide such a feature.

**Comment by nguyenquanghoang** [comment] 2024-07-22 09:55
@wojtekn Yes, This would be inconvenient. I hope it will have a solution

**Comment by katinthehatsite** [comment] 2024-08-29 11:38
Testing this on macOS and I can't reproduce this on my end:

<img width="291" alt="Ảnh màn hình 2024-08-29 lúc 1 35 50 CH" src="https://github.com/user-attachments/assets/cceb329f-4bb4-4243-b48c-cf27fb101db6">

This was tested on MacBook Pro, macOS Sonoma 14.5 and the most recent version of Studio.

**Comment by nguyenquanghoang** [comment] 2024-08-29 12:34
@katinthehatsite Yes this has been fixed

**Comment by katinthehatsite** [comment] 2024-08-29 12:43
@nguyenquanghoang  Great, if this is no longer an issue, we can close this report 👍 

For the translation bit, we can open a separate issue to look into it.

**Closed as completed by katinthehatsite** 2024-08-29 12:43 UTC
