### ISSUE TITLE
Importing: Downloading media fails

### ISSUE THREAD

**Issue by jasmussen** [Automattic/studio#33] opened 2024-04-25 13:57 UTC
### Quick summary

I'm trying to import an XML file I've exported from another WordPress site, with the goal of having some demo content.

The content imports, but not media and attachments. I'm getting a simple "Failed" message when I try to import.

### Steps to reproduce

1. Export content from a WordPress site, ensure it has posts or pages and images inserted in those.
2. Import it in a Studio site

### What you expected to happen

Images and content should both successfully import.

### What actually happened

Got a failure message for media.

### Impact

One

### Available workarounds?

No but the app is still usable

### Platform

Mac Silicon

**Comment by jeff-at-livecanvas** [comment] 2024-04-26 13:02
A couple attempts at writing a file brought to an error. Could be that the issue is about writing files in general?

**Comment by jbodnar2** [comment] 2024-04-29 13:28
Encountered same issue in regard to media and WP export/import. Media won't import. No issue with individual media uploads.

**Comment by wojtekn** [comment] 2024-05-16 14:04
It's fixed in 1.0.2: https://github.com/Automattic/studio/releases/tag/v1.0.2

**Closed as completed by wojtekn** 2024-05-16 14:04 UTC
