### ISSUE TITLE
theme activate error on MAC M1

### ISSUE THREAD

**Issue by sanskritkm** [Automattic/studio#145] opened 2024-05-18 04:42 UTC
### Quick summary

seem like permission issue when install new theme like Astra Theme, this theme will auto activate or import template from internet but it look like error during activation and wrong location.

### Steps to reproduce

install theme Astra and the theme auto activate then error

### What you expected to happen

after theme activate it error seem like wrong location.

### What actually happened

<img width="980" alt="image" src="https://github.com/Automattic/studio/assets/17005582/dea2680d-c288-49f1-8e11-702cfb6503fd">

### Impact

One

### Available workarounds?

No and the app is unusable

### Platform

Mac Silicon

**Comment by wojtekn** [comment] 2024-05-20 10:45
Hi @kdamsmt ! Thanks for your report. I tried those steps with Studio 1.0.2 and couldn't reproduce it:
1. Create a new site in Studio
2. Open WP Admin
3. Navigate to Appearance -> Themes
4. Click Add New Theme
5. Search for Astra
6. In the Astra theme block, click Install and then Activate

The theme was activated without an error, and the change is visible in the frontend.

Could you share more details about your setup and confirm that you followed the same steps?

**Comment by faisalahammad** [comment] 2024-05-26 15:32
I have tried the latest version of the **Astra** theme (`v4.6.15`) but was unable to reproduce the issue. I have enabled WP Debug but without success. 

To resolve the issue, I recommend following the instructions from the article here: https://www.malcare.com/blog/cannot-modify-header-information-headers-already-sent-by-error/.

Screenshot:

![WP Debug@2x](https://github.com/Automattic/studio/assets/13257516/267d0191-03dc-456d-a7ad-bd5d33c1cf59)

**Comment by wojtekn** [comment] 2024-07-26 10:32
I'm closing the issue as we couldn't reproduce it.

**Closed as completed** 2024-07-31 07:37 UTC
