### ISSUE TITLE
Icon to close the Settings modal has a very small click point.

### ISSUE THREAD

**Issue by markbiek** [Automattic/studio#507] opened 2024-09-03 18:01 UTC
### Quick summary

The icon to close the Settings modal has a very small click point that's mostly _below_ the actual icon.

![CleanShot 2024-09-03 at 13 58 46@2x](https://github.com/user-attachments/assets/2863c419-870d-4df3-87f5-e0dbe1ea8bf0)

### Steps to reproduce

1. Open Studio.
2. Go to Studio -> Settings
3. Hover the mouse over the close icon. You'll notice that most of the icon isn't actually clickable. The click point is mostly below the icon.

### What you expected to happen

I expected to be able to click anywhere on the `X` to close the settings.

### What actually happened

Large portions of the icon aren't clickable.

https://github.com/user-attachments/assets/15cb33a5-afdb-47f5-99ca-0235ab5ea1e2

### Impact

One

### Available workarounds?

No but the app is still usable

### Platform

Mac Silicon

### Logs or notes

OSX Sonoma 14.5

Studio Version 1.1.1-dev.2287249

**Comment by danielbachhuber** [comment] 2024-09-03 18:57
Thanks for the report, @markbiek !

Feel free to submit a pull request if you'd like 😊

**Comment by renancarvalho** [comment] 2024-09-05 07:34
I was unable to reproduce this issue, I checked using studio `version 1.1.0` and the close button on the setting's modal was with the right clickable area, I checked its width and height and seems correct.

**Comment by markbiek** [comment] 2024-09-05 12:18
> I was unable to reproduce this issue, I checked using studio `version 1.1.0` and the close button on the setting's modal was with the right clickable area, I checked its width and height and seems correct.

I was using `1.1.1-dev.2287249`. Is it possible this is a new issue?

**Comment by markbiek** [comment] 2024-09-05 12:19
I just upgraded to `1.1.1-dev.944bd21` and I'm still seeing the same behavior.

**Comment by wojtekn** [comment] 2024-09-10 09:40
@markbiek I couldn't reproduce it using 1.1.1-dev.944bd21. The whole area shown when I focus button is clickable:

![Screenshot 2024-09-10 at 11 39 10](https://github.com/user-attachments/assets/c5b39192-c93d-43d4-9608-8b8b0a3ac43f)

Would you mind trying to focus the button using keyboard navigation to see what area it focuses on and share a screenshot showing the whole app window?

**Comment by inaikem** [comment] 2024-11-12 07:55
Group Triage: Greetings @wojtekn, I'd like to work on a process for Studio issues that bypasses PA triage since the team appears to do a very good job of raising and working on them directly. Do you have any suggestions for streamlining?

**Comment by wojtekn** [comment] 2024-11-12 08:02
> Do you have any suggestions for streamlining?

Should we simply exclude studio issues from triage process?

**Comment by wojtekn** [comment] 2024-11-28 12:12
Closing as we couldn't reproduce this issue.

**Closed as not planned by wojtekn** 2024-11-28 12:12 UTC
